### ISSUE TITLE
Did not receive ping response within timeout

### ISSUE THREAD

**Issue by JosephM101** [rhasspy/wyoming-satellite#59] opened 2024-01-17 03:26 UTC
I don't know what the issue is. I tried multiple reinstalls of Raspberry Pi OS Lite and re-configuring the satellite using the built-in `installer` tool. But after the satellite starts, it connects, then fails 5 seconds later with:
```
WARNING:root:Did not receive ping response within timeout
INFO:root:Disconnected from server
```

The weird thing is that this used to work. I had no problems initially, and have no clue what could have possibly changed.
![image](https://github.com/rhasspy/wyoming-satellite/assets/28277730/4a221bcf-c53b-4264-acc1-fba6b2605a5d)

I am running Home Assistant 2024.1.3

**Comment by llluis** [comment] 2024-01-17 04:02
This is a new code pushed by @synesthesiam a few hours ago... 33e6d80786ed888ecb662dcdf597ef0cb2c67937
I see a corresponding commit in the core of Home Assistant for the new wyoming protocol 1.5.0, but, don't know when those will be pushed. I would say right now current version is broken if you are not in the dev branch of Home Assistant.

I'm testing how to rollback to the previous version...

**Comment by llluis** [comment] 2024-01-17 04:15
I just tested a temporary fix:
- in the wyoming-satellite folder, `git reset --hard db5918e` (the last commit before the changes)
- `.venv/bin/pip3 install wyoming==1.4.2`

Restart your satellite.

**Comment by JosephM101** [comment] 2024-01-17 04:43
> I just tested a temporary fix:
> 
>     * in the wyoming-satellite folder, `git reset --hard db5918e` (the last commit before the changes)
> 
>     * `.venv/bin/pip3 install wyoming==1.4.2`
> 
> 
> Restart your satellite.

I tried that and got closer, but now I'm having different problems.

![image](https://github.com/rhasspy/wyoming-satellite/assets/28277730/9f799932-7f3e-4f64-ad64-09cd9cccfada)
![image](https://github.com/rhasspy/wyoming-satellite/assets/28277730/e8da3cba-bcc0-41bc-9983-51c251f509e1)
![image](https://github.com/rhasspy/wyoming-satellite/assets/28277730/9fca6009-4a09-49c3-90ea-51f7352ae8ad)

I just wish HASS would tell me exactly what was going wrong. The logs are super vague, even when the level is set to debug. Quite frustrating...

**Comment by llluis** [comment] 2024-01-17 04:53
I see you are using remote wake word detection (in HA and not satellite). Even if I change my config to this I can't reproduce your error.

Do you have your pipeline correctly configured in there? (wake word installed, etc)

**Comment by JosephM101** [comment] 2024-01-17 04:57
Yeah, everything is installed properly. I even uninstalled then reinstalled all of the addons, and... nothing. I did, however, just finish enabling local openWakeWord on the Pi, and it seems to be working now for the most part. It responds to queries.

**Comment by JosephM101** [comment] 2024-01-17 04:59
Does this have to do with some kind of code change in HASS 2024.1.3? Because I might have a backup of the previous version. Or might it be a better idea to try a dev build of Home Assistant?

**Comment by llluis** [comment] 2024-01-17 05:01
> Does this have to do with some kind of code change in HASS 2024.1.3? Because I might have a backup of the previous version. Or might it be a better idea to try a dev build of Home Assistant?

I'm on the same version and everything works properly... I would guess you are missing something in your Assistant configuration.
In your Wyoming integration, you will see a device for the satellite. Make sure your pipeline is selected there.
Also, go to the Voice Assistant settings for the desired assistant  and make sure everything is configured there. Specially the wake word at the end.

I would wait some feedback from synesthesiam before going down the dev build route...

**Comment by llluis** [comment] 2024-01-17 05:03
> EDIT: Should've really read back a few posts; you mentioned a code push for Wyoming Protocol V1.5.0.

Thing is, if my understanding is correct, we will see this only when a new HA version will be released, which could be long...

**Comment by JosephM101** [comment] 2024-01-17 05:05
I've already gone through those a bunch. Guess it wouldn't hurt to try again.

I can spin up an experimental HASS VM for testing on the dev branch when I get a chance.

**Comment by preimmortal** [comment] 2024-01-17 05:05
There's a new build of HA that works for me:  `ghcr.io/home-assistant/home-assistant:2024.2.0.dev20240117`

**Comment by JosephM101** [comment] 2024-01-17 05:05
How do I apply that?

**Comment by preimmortal** [comment] 2024-01-17 05:06
Are you running HA via docker or HA OS? I forgot to mention my link was specifically a docker build

**Comment by JosephM101** [comment] 2024-01-17 05:07
HA OS

**Comment by preimmortal** [comment] 2024-01-17 05:08
Ah, yeah you might need to build from source in that case :(

**Comment by JosephM101** [comment] 2024-01-17 05:08
What about this?

![image](https://github.com/rhasspy/wyoming-satellite/assets/28277730/99b808fd-1275-4bd8-8285-1e9309e238d8)

**Comment by llluis** [comment] 2024-01-17 05:10
This should work: https://www.home-assistant.io/common-tasks/os/#run-a-development-version

**Comment by JosephM101** [comment] 2024-01-17 05:12
Okay, I'll try that. I need to login to the KVM host.

**Comment by JosephM101** [comment] 2024-01-17 05:30
Dude, you're a genius. Thank you so much! It's all working, including server-side openWakeWord.

Hopefully I'm not angering the gods and potentially jinxing myself by saying that.

**Comment by pkkrusty** [comment] 2024-01-17 12:00
What kind of timeframe are we looking at for a normal fix (HA OS update)? Weeks, or hours? I just built a satellite on a Zero 2 W and got the timeout issue. Everything works for a few seconds, then timeouts. In you all's more expert opinions, is it easier to drop the satellite down to 1.4.x or push HA OS to the dev branch?

```
INFO:root:Ready
DEBUG:root:Detected IP: 192.168.1.29
DEBUG:root:Zeroconf discovery enabled (name=e45f013f8db8, host=None)
DEBUG:root:Connecting to mic service: ['arecord', '-D', 'plughw:CARD=CameraB409241,DEV=0', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
INFO:root:Connected to services
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Connected to mic service
DEBUG:root:Server set: 2617645925395
INFO:root:Connected to server
INFO:root:Streaming audio
DEBUG:root:Wake word detected
WARNING:root:Did not receive ping response within timeout
DEBUG:root:Server disconnected
INFO:root:Disconnected from server
```

**Comment by pkkrusty** [comment] 2024-01-17 14:13
Ah I was missing the git reset command when I downgraded to 1.4.2, so I switched to the dev branch of HA OS and that is working correctly. I'll stick to that until the main branch gets the commit.

**Comment by synesthesiam** [comment] 2024-01-17 18:51
Sorry, everyone. I forgot that the HA side of things was in nightly only, so I've pushed a new commit here to only enable pinging if the server supports it.

**Closed** 2024-01-18 21:39 UTC

**Comment by tombul** [comment] 2024-02-12 08:34
i know this is solved and closed, but as i run into the same or for me very similar, error message, i am wondering if there is a way to just ignore the ping or disable it temporarily? i am kinda lost on how to proceed to ignore the ping.

in my case i get 
```shell
WARNING:root:Did not receive ping response within timeout
INFO:root:Disconnected from server
``` 
but only when i have a long response that the voice satellite is sending to my sonos. there does not seem to be anything wrong with the response, besides the fact that the voice satellite aborts after not receiving a ping. this usually happens while sonos is still talking.

**Comment by llluis** [comment] 2024-02-12 15:06
There's no way currently to ignore or change the ping without modifying the code.
If you want to modify the code, you can try to comment this line:

https://github.com/rhasspy/wyoming-satellite/blob/8850100ca658a80708e562e6741739ed27c91f99/wyoming_satellite/satellite.py#L243

All the scripting and http calls you are doing seem to be synchronous and blocking the execution of the satellite.
The ping timeout is 5 seconds. I just tested a reply of several seconds, and had no issues.

**Comment by tombul** [comment] 2024-02-12 20:01
thank you for your advice @llluis !

commenting that line out and reloading the wyoming-satellite service did remove the warning about the ping.
unfortunately it brought up some kind of unknown error 524 which seems to be some error with snd read task.

the warning regarding the missing ping is actually not that big of a deal for me.
it's just a little annoying that the satellite reconnects and blinks red and green while my announcement is being given on a separate speaker. 
and then the logs show that curl returns the result of the post call.

so i enable the ping back on for now. do you by any chance know if there is a way to increae the timeout for this ping? 
i already tried sending the curl calls to the background via & behind the shell command but that did not help. so i am kinda wondering if i have to live with it for long text responses via post calls to external speakers.

**Comment by llluis** [comment] 2024-02-12 20:12
> do you by any chance know if there is a way to increae the timeout for this ping? 

https://github.com/rhasspy/wyoming-satellite/blob/8850100ca658a80708e562e6741739ed27c91f99/wyoming_satellite/satellite.py#L40

**Comment by vitalized** [comment] 2024-02-27 20:23
` _PONG_TIMEOUT: Final = 20 `
Thanks, changing the timeout has fixed the server disconnect for me!
